name: api
description: A Terco Online project

environment:
  sdk: '>=2.14.0'

dependencies:
  functions_framework: ^0.4.1
  reflectable: ^3.0.8
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_router_generator: ^1.0.4
  postgres: ^2.5.1
  dartnate: ^0.0.1

dev_dependencies:
  build_runner: ^2.2.1
  functions_framework_builder: ^0.4.7
  http: ^0.13.5
  lints: ^2.0.0
  test: ^1.21.6
  test_process: ^2.0.2